[workspace]
members = ["ploidy", "ploidy-pointer", "ploidy-pointer-derive", "ploidy-util"]
resolver = "2"

[workspace.package]
version = "0.1.3"
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/linabutler/ploidy"
keywords = ["openapi", "swagger"]

[workspace.dependencies]
ploidy-pointer = { path = "ploidy-pointer", version = "0.1.3" }
ploidy-pointer-derive = { path = "ploidy-pointer-derive", version = "0.1.3" }

[workspace.lints.rust]
unsafe_code = "forbid"
