[workspace]
members = [
    "ploidy",
    "ploidy-codegen-rust",
    "ploidy-codegen-typescript",
    "ploidy-core",
    "ploidy-pointer",
    "ploidy-pointer-derive",
    "ploidy-util",
]
resolver = "2"

[workspace.package]
version = "0.9.0"
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/linabutler/ploidy"
keywords = ["codegen", "openapi", "swagger"]
rust-version = "1.89"

[workspace.dependencies]
either = "1"
oxc_allocator = "0.113"
oxc_ast = "0.113"
oxc_codegen = "0.113"
oxc_span = "0.113"
indoc = "2"
ploidy-codegen-rust = { path = "ploidy-codegen-rust", version = "0.9.0" }
ploidy-codegen-typescript = { path = "ploidy-codegen-typescript", version = "0.9.0" }
ploidy-core = { path = "ploidy-core", version = "0.9.0" }
ploidy-pointer = { path = "ploidy-pointer", version = "0.9.0" }
ploidy-pointer-derive = { path = "ploidy-pointer-derive", version = "0.9.0" }
pretty_assertions = "1"
ref-cast = "1"

[workspace.lints.rust]
unsafe_code = "forbid"
