[workspace]
members = [
    "ploidy",
    "ploidy-codegen-rust",
    "ploidy-core",
    "ploidy-pointer",
    "ploidy-pointer-derive",
    "ploidy-util",
]
resolver = "2"

[workspace.package]
version = "0.5.1"
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/linabutler/ploidy"
keywords = ["codegen", "openapi", "swagger"]
rust-version = "1.89"

[workspace.dependencies]
either = "1"
ploidy-codegen-rust = { path = "ploidy-codegen-rust", version = "0.5.0" }
ploidy-core = { path = "ploidy-core", version = "0.5.0" }
ploidy-pointer = { path = "ploidy-pointer", version = "0.5.0" }
ploidy-pointer-derive = { path = "ploidy-pointer-derive", version = "0.5.0" }

[workspace.lints.rust]
unsafe_code = "forbid"
