[workspace]
members = ["ploidy", "ploidy-util"]
resolver = "2"

[workspace.package]
version = "0.1.3"
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/linabutler/ploidy"
keywords = ["openapi", "swagger"]

[workspace.lints.rust]
unsafe_code = "forbid"
